Repository openvinotoolkit/openvino_notebooks, pull requests merged in 2022-05, with the labels that each got.

#550 Add tagging for notebooks
  .ci/keywords.json
  .ci/tagger.py
  .github/workflows/generate_tags.yml
Labels: documentation

#543 Removed openvino_env kernel from contribution guide
  CONTRIBUTING.md
Labels: documentation

#473 217 vision deblur
  README.md
  notebooks/217-vision-deblur/217-vision-deblur.ipynb
  notebooks/217-vision-deblur/README.md
  notebooks/README.md
Labels: gsoc

#524 204 NLP Document Inference Entity Extraction Demo
  README.md
  notebooks/204-named-entity-recognition/204-named-entity-recognition.ipynb
  notebooks/204-named-entity-recognition/README.md
  notebooks/204-named-entity-recognition/data/vocab.txt
  notebooks/204-named-entity-recognition/tokens_bert.py
  notebooks/README.md
Labels: new notebook
