Repository openvinotoolkit/openvino_notebooks, pull requests merged in 2022-11, with the labels that each got.

#646 Amazon SageMaker
  README.md
  notebooks/README.md
Labels: enhancement

#661 prevent 203 failed by timeout
  .github/workflows/nbval.yml
Labels: enhancement

#616 add 224-3D-segmentation
  README.md
  notebooks/224-3D-segmentation-point-clouds/224-3D-segmentation-point-clouds.ipynb
  notebooks/224-3D-segmentation-point-clouds/README.md
  notebooks/224-3D-segmentation-point-clouds/data/chair.pts
  notebooks/README.md
Labels: new notebook

#681 try fix precommit docker
  .docker/Pipfile.lock
Labels: fixing

#677 115 update with infer queue
  notebooks/115-async-api/115-async-api.ipynb
  notebooks/115-async-api/README.md
Labels: enhancement

#660 Improve OOB API demonstration
  notebooks/002-openvino-api/002-openvino-api.ipynb
  notebooks/113-image-classification-quantization/113-image-classification-quantization.ipynb
  notebooks/114-quantization-simplified-mode/114-quantization-simplified-mode.ipynb
  notebooks/201-vision-monodepth/201-vision-monodepth.ipynb
  notebooks/202-vision-superresolution/202-vision-superresolution-image.ipynb
  notebooks/202-vision-superresolution/202-vision-superresolution-video.ipynb
  notebooks/204-named-entity-recognition/204-named-entity-recognition.ipynb
  notebooks/205-vision-background-removal/205-vision-background-removal.ipynb
  notebooks/213-question-answering/213-question-answering.ipynb
  notebooks/220-yolov5-accuracy-check-and-quantization/220-yolov5-accuracy-check-and-quantization.ipynb
  notebooks/223-gpt2-text-prediction/223-gpt2-text-prediction.ipynb
  notebooks/302-pytorch-quantization-aware-training/302-pytorch-quantization-aware-training.ipynb
  notebooks/305-tensorflow-quantization-aware-training/305-tensorflow-quantization-aware-training.ipynb
  notebooks/402-pose-estimation-webcam/402-pose-estimation.ipynb
  notebooks/405-paddle-ocr-webcam/405-paddle-ocr-webcam.ipynb
  notebooks/405-paddle-ocr-webcam/README.md
Labels: enhancement
