Repository openvinotoolkit/openvino_notebooks, pull requests merged in 2022-04, with the labels that each got.

#463 Wav2vec2
  README.md
  notebooks/107-speech-recognition-quantization/107-speech-recognition-quantization.ipynb
  notebooks/107-speech-recognition-quantization/README.md
  notebooks/README.md
Labels: new notebook

#514 Update 214
  README.md
  notebooks/214-vision-paddle-classification/214-vision-paddle-classification.ipynb
  notebooks/README.md
Labels: enhancement

#414 Added notebook for the Simplified mode in POT
  README.md
  notebooks/114-quantization-simplified-mode/114-quantization-simplified-mode.ipynb
  notebooks/114-quantization-simplified-mode/README.md
  notebooks/README.md
Labels: new notebook

#518 Changing domain in hyperlinks
  notebooks/001-hello-world/001-hello-world.ipynb
  notebooks/003-hello-segmentation/003-hello-segmentation.ipynb
  notebooks/003-hello-segmentation/README.md
  notebooks/004-hello-detection/README.md
  notebooks/101-tensorflow-to-openvino/101-tensorflow-to-openvino.ipynb
  notebooks/101-tensorflow-to-openvino/README.md
  notebooks/102-pytorch-onnx-to-openvino/102-pytorch-onnx-to-openvino.ipynb
  notebooks/102-pytorch-onnx-to-openvino/README.md
  notebooks/103-paddle-onnx-to-openvino/103-paddle-onnx-to-openvino-classification.ipynb
  notebooks/103-paddle-onnx-to-openvino/README.md
  notebooks/105-language-quantize-bert/105-language-quantize-bert.ipynb
  notebooks/105-language-quantize-bert/README.md
  notebooks/110-ct-segmentation-quantize/110-ct-segmentation-quantize.ipynb
  notebooks/110-ct-segmentation-quantize/README.md
  notebooks/111-detection-quantization/111-detection-quantization.ipynb
  notebooks/112-pytorch-post-training-quantization-nncf/112-pytorch-post-training-quantization-nncf.ipynb
  notebooks/112-pytorch-post-training-quantization-nncf/README.md
  notebooks/113-image-classification-quantization/113-image-classification-quantization.ipynb
  notebooks/113-image-classification-quantization/README.md
  notebooks/201-vision-monodepth/201-vision-monodepth.ipynb
  notebooks/205-vision-background-removal/205-vision-background-removal.ipynb
  notebooks/206-vision-paddlegan-anime/206-vision-paddlegan-anime.ipynb
  notebooks/208-optical-character-recognition/208-optical-character-recognition.ipynb
  notebooks/208-optical-character-recognition/README.md
  notebooks/209-handwritten-ocr/209-handwritten-ocr.ipynb
  notebooks/209-handwritten-ocr/README.md
  notebooks/210-ct-scan-live-inference/210-ct-scan-live-inference.ipynb
  notebooks/301-tensorflow-training-openvino/301-tensorflow-training-openvino-pot.ipynb
  notebooks/301-tensorflow-training-openvino/README.md
  notebooks/302-pytorch-quantization-aware-training/302-pytorch-quantization-aware-training.ipynb
  notebooks/302-pytorch-quantization-aware-training/README.md
  notebooks/305-tensorflow-quantization-aware-training/305-tensorflow-quantization-aware-training.ipynb
  notebooks/305-tensorflow-quantization-aware-training/README.md
  notebooks/403-action-recognition-webcam/README.md
Labels: documentation

#501 106 auto device
  README.md
  notebooks/106-auto-device/106-auto-device.ipynb
  notebooks/106-auto-device/README.md
  notebooks/README.md
Labels: new notebook

#538 Change NMS From x1y1x2y2 to x1y1wh Bug Fix
  notebooks/401-object-detection-webcam/401-object-detection.ipynb
Labels: bug

#461 214 Vehicle Detection And Recognition with OpenVINO
  README.md
  README_cn.md
  notebooks/218-vehicle-detection-and-recognition/218-vehicle-detection-and-recognition.ipynb
  notebooks/218-vehicle-detection-and-recognition/README.md
  notebooks/README.md
Labels: gsoc
