Repository openvinotoolkit/openvino_notebooks, pull requests merged in 2022-12, with the labels that each got.

#689 Removed rule of imports
  CONTRIBUTING.md
Labels: documentation

#676 404 Live style transfer notebook
  README.md
  notebooks/404-style-transfer-webcam/404-style-transfer.ipynb
  notebooks/404-style-transfer-webcam/README.md
  notebooks/README.md
Labels: new notebook

#698 update 224 datasets download links
  notebooks/224-3D-segmentation-point-clouds/224-3D-segmentation-point-clouds.ipynb
Labels: enhancement

#704 Unignore 107, 114 and 115 notebooks
  .github/workflows/nbval.yml
  .github/workflows/nbval_precommit.yml
  notebooks/107-speech-recognition-quantization/107-speech-recognition-quantization.ipynb
Labels: fixing

#703 update stable diffusion notebooks according the latest API changes
  notebooks/225-stable-diffusion-text-to-image/225-stable-diffusion-text-to-image.ipynb
  notebooks/225-stable-diffusion-text-to-image/requirements.txt
Labels: enhancement

#678 Add whisper notebook
  .docker/Pipfile
  .docker/Pipfile.lock
  README.md
  notebooks/227-whisper-subtitles-generation/227-whisper-subtitles-generation.ipynb
  notebooks/227-whisper-subtitles-generation/README.md
  notebooks/README.md
  requirements.txt
Labels: new notebook

#688 103 convert paddle to OV without legacy ONNX path
  .docker/Pipfile
  .docker/Pipfile.lock
  README.md
  README_cn.md
  notebooks/103-paddle-onnx-to-openvino/README.md
  notebooks/103-paddle-to-openvino/103-paddle-to-openvino-classification.ipynb
  notebooks/103-paddle-to-openvino/README.md
  notebooks/103-paddle-to-openvino/data/coco_close.png
  notebooks/README.md
  requirements.txt
Labels: enhancement

#673 102 replace fastseg model
  .docker/Pipfile
  .docker/Pipfile.lock
  notebooks/102-pytorch-onnx-to-openvino/102-pytorch-onnx-to-openvino.ipynb
  notebooks/102-pytorch-onnx-to-openvino/README.md
  notebooks/102-pytorch-onnx-to-openvino/data/street.jpg
  notebooks/219-knowledge-graphs-conve/219-knowledge-graphs-conve.ipynb
  notebooks/220-yolov5-accuracy-check-and-quantization/220-yolov5-accuracy-check-and-quantization.ipynb
  requirements.txt
Labels: enhancement

#722 Update with the PaddleOCR V3 model
  .github/workflows/nbval_precommit.yml
  notebooks/405-paddle-ocr-webcam/405-paddle-ocr-webcam.ipynb
  notebooks/405-paddle-ocr-webcam/README.md
Labels: enhancement

#715 CLIP zero shot image classification notebook
  README.md
  notebooks/228-clip-zero-shot-image-classification/228-clip-zero-shot-image-classification.ipynb
  notebooks/228-clip-zero-shot-image-classification/README.md
  notebooks/228-clip-zero-shot-image-classification/data/coco.jpg
  notebooks/README.md
Labels: new notebook

#726 remove unused requirements
  .docker/Pipfile
  .docker/Pipfile.lock
  requirements.txt
Labels: enhancement

#606 406 Human Pose Estimation 3D
  README.md
  README_cn.md
  notebooks/406-3D-pose-estimation-webcam/406-3D-pose-estimation.ipynb
  notebooks/406-3D-pose-estimation-webcam/README.md
  notebooks/406-3D-pose-estimation-webcam/engine/__init__.py
  notebooks/406-3D-pose-estimation-webcam/engine/engine3js.py
  notebooks/406-3D-pose-estimation-webcam/engine/legacy_pose_extractor.py
  notebooks/406-3D-pose-estimation-webcam/engine/one_euro_filter.py
  notebooks/406-3D-pose-estimation-webcam/engine/parse_poses.py
  notebooks/406-3D-pose-estimation-webcam/engine/pose.py
  notebooks/README.md
Labels: new notebook

#718 Change copy model stage in 208 notebook
  notebooks/208-optical-character-recognition/208-optical-character-recognition.ipynb
Labels: enhancement

#692 Update script to use cache_dir
  .gitignore
  notebooks/201-vision-monodepth/201-vision-monodepth.ipynb
  notebooks/cache/empty
Labels: enhancement

#732 update supported python versions and OS
  README.md
  README_cn.md
  notebooks/README.md
Labels: documentation

#736 allow store output in notebooks
  .ci/patch_notebooks.py
  CONTRIBUTING.md
Labels: enhancement

#735 add scheduler to convert notebook run
  .github/workflows/convert_notebooks.yml
Labels: enhancement
