Repository openvinotoolkit/openvino_notebooks, pull requests merged in 2023-02, with the labels that each got.

#805 225: add VAE encoder conversion
  README.md
  notebooks/225-stable-diffusion-text-to-image/225-stable-diffusion-text-to-image.ipynb
  notebooks/225-stable-diffusion-text-to-image/README.md
  notebooks/README.md
Labels: enhancement

#808 add 117 Model server
  .docker/.s2i/bin/test
  README.md
  notebooks/117-model-server/117-model-server.ipynb
  notebooks/117-model-server/README.md
  notebooks/README.md
Labels: new notebook, wip

#820 Update README_cn.md
  README_cn.md
Labels: documentation

#788 108: Working with GPUs in OpenVINO notebook
  notebooks/108-gpu-device/108-gpu-device.ipynb
  notebooks/108-gpu-device/README.md
Labels: new notebook

#811 Add tutorial for preprocessing API
  README.md
  notebooks/118-optimize-preprocessing/118-optimize-preprocessing.ipynb
  notebooks/118-optimize-preprocessing/README.md
  notebooks/README.md
Labels: new notebook

#838 Fixed 213 for documentation
  notebooks/213-question-answering/213-question-answering.ipynb
Labels: documentation, fixing

#827 212: speaker diarization
  README.md
  notebooks/212-pyannote-speaker-diarization/212-pyannote-speaker-diarization.ipynb
  notebooks/212-pyannote-speaker-diarization/README.md
  notebooks/212-pyannote-speaker-diarization/requirements.txt
  notebooks/README.md
Labels: new notebook

#847 Download omz models directly to model dir instead of user home
  notebooks/104-model-tools/104-model-tools.ipynb
  notebooks/208-optical-character-recognition/208-optical-character-recognition.ipynb
  notebooks/217-vision-deblur/217-vision-deblur.ipynb
Labels: enhancement

#853 Update binder links for notebooks
  README.md
  notebooks/206-vision-paddlegan-anime/README.md
  notebooks/207-vision-paddlegan-superresolution/README.md
  notebooks/209-handwritten-ocr/README.md
  notebooks/212-pyannote-speaker-diarization/README.md
  notebooks/217-vision-deblur/README.md
  notebooks/229-distilbert-sequence-classification/README.md
  notebooks/README.md
Labels: documentation

#839 214: grammar correction notebook
  README.md
  notebooks/214-grammar-correction/214-grammar-correction.ipynb
  notebooks/214-grammar-correction/README.md
  notebooks/README.md
Labels: new notebook

#844 notebooks conversion
  .ci/convert_notebooks.py
  .ci/convert_notebooks.sh
  .ci/ignore_convert_execution.txt
  .ci/ignore_convert_full.txt
  .github/workflows/convert_notebooks.yml
Labels: fixing

#826 117 construct model dir
  notebooks/117-model-server/117-model-server.ipynb
Labels: enhancement

#870 Fixed benchmark output for 301
  notebooks/301-tensorflow-training-openvino/301-tensorflow-training-openvino-pot.ipynb
Labels: fixing
