Repository openvinotoolkit/openvino_notebooks, pull requests merged in 2023-05, with the labels that each got.

#1034 Update README.md
  README.md
Labels: documentation

#897 [GSoC] Text Generation Notebook Using GPT-Neo
  README.md
  README_cn.md
  notebooks/223-gpt2-text-prediction/223-gpt2-text-prediction.ipynb
  notebooks/223-gpt2-text-prediction/README.md
  notebooks/223-text-prediction/223-text-prediction.ipynb
  notebooks/223-text-prediction/README.md
Labels: new notebook, gsoc, tech_review: ready

#1057 Fixes for macOS
  notebooks/107-speech-recognition-quantization/107-speech-recognition-quantization-data2vec.ipynb
  notebooks/107-speech-recognition-quantization/107-speech-recognition-quantization-wav2vec2.ipynb
Labels: enhancement

#1053 110 fix flow
  notebooks/110-ct-segmentation-quantize/110-ct-segmentation-quantize-nncf.ipynb
Labels: fix

#1019 Added intelligent queue management recipe
  recipes/intelligent-queue-management/README.md
  recipes/intelligent-queue-management/app.py
  recipes/intelligent-queue-management/convert_and_optimize.py
  recipes/intelligent-queue-management/data/pexels-catia-matos-1604200.jpg
  recipes/intelligent-queue-management/docs/convert-and-optimize-the-model.ipynb
  recipes/intelligent-queue-management/docs/run-the-application.ipynb
  recipes/intelligent-queue-management/main.py
  recipes/intelligent-queue-management/model/.gitkeep
  recipes/intelligent-queue-management/requirements.txt
  recipes/intelligent-queue-management/utils.py
  recipes/intelligent-queue-management/zones.json
Labels: AI recipe

#1039 238 IF by DeepFloyd
  .ci/ignore_convert_execution.txt
  .docker/.s2i/bin/test
  .github/workflows/treon.yml
  .github/workflows/treon_precommit.yml
  README.md
  notebooks/238-deeployd-if/238-deep-floyd-if.ipynb
  notebooks/238-deeployd-if/README.md
Labels: new notebook

#1089 Fixed docs conversion
  .ci/ignore_convert_execution.txt
  .ci/ignore_convert_full.txt
  .ci/ignore_treon_linux.txt
  .ci/ignore_treon_mac.txt
  .github/workflows/treon.yml
  .github/workflows/treon_precommit.yml
  notebooks/108-gpu-device/108-gpu-device.ipynb
  notebooks/109-performance-tricks/109-latency-tricks.ipynb
  notebooks/227-whisper-subtitles-generation/227-whisper-subtitles-generation.ipynb
Labels: enhancement

#1044 Add notebook for attention-center tflite model
  README.md
  notebooks/002-openvino-api/002-openvino-api.ipynb
  notebooks/216-attention-center/216-attention-center.ipynb
  notebooks/216-attention-center/README.md
Labels: new notebook

#1093 Paularamo/removing sam51
  README.md
  notebooks/237-segment-anything/237-segment-anything-fiftyone.ipynb
  notebooks/237-segment-anything/README.md
Labels: fix
