Repository openvinotoolkit/openvino_notebooks, pull requests merged in 2023-01, with the labels that each got.

#749 remove code snippets duplication from notebook_utils.ipynb
  notebooks/utils/notebook_utils.ipynb
Labels: enhancement

#702 Arunima Fork for Openvino Notebooks
  README.md
  notebooks/229-distilbert-sequence-classification/229-distilbert-sequence-classification.ipynb
  notebooks/229-distilbert-sequence-classification/README.md
  notebooks/README.md
  notebooks/data/text/food_reviews.txt
Labels: new notebook

#758 workaround omz issues in 104
  notebooks/104-model-tools/104-model-tools.ipynb
Labels: fixing

#754 fix matplotlib version for yolov7 notebook
  .docker/Pipfile
  .docker/Pipfile.lock
  notebooks/110-ct-segmentation-quantize/110-ct-segmentation-quantize-nncf.ipynb
  notebooks/112-pytorch-post-training-quantization-nncf/112-pytorch-post-training-quantization-nncf.ipynb
  notebooks/226-yolov7-optimization/226-yolov7-optimization.ipynb
  notebooks/302-pytorch-quantization-aware-training/302-pytorch-quantization-aware-training.ipynb
  notebooks/305-tensorflow-quantization-aware-training/305-tensorflow-quantization-aware-training.ipynb
  requirements.txt
Labels: fixing

#769 Fix the visualization issue for 203
  notebooks/203-meter-reader/203-meter-reader.ipynb
Labels: enhancement

#765 refactor gpt2 notebook to use original model
  .github/workflows/nbval_precommit.yml
  notebooks/223-gpt2-text-prediction/223-gpt2-text-prediction.ipynb
  notebooks/223-gpt2-text-prediction/README.md
Labels: enhancement

#775 Replace omz_downloader/converter to native download/mo
  notebooks/215-image-inpainting/215-image-inpainting.ipynb
Labels: enhancement

#779 203 set dimension bound for dynamic shape
  notebooks/203-meter-reader/203-meter-reader.ipynb
Labels: enhancement

#780 More fixes for macOS
  notebooks/105-language-quantize-bert/105-language-quantize-bert.ipynb
  notebooks/107-speech-recognition-quantization/107-speech-recognition-quantization.ipynb
  notebooks/206-vision-paddlegan-anime/206-vision-paddlegan-anime.ipynb
  notebooks/214-vision-paddle-classification/214-vision-paddle-classification.ipynb
  notebooks/229-distilbert-sequence-classification/229-distilbert-sequence-classification.ipynb
  notebooks/305-tensorflow-quantization-aware-training/305-tensorflow-quantization-aware-training.ipynb
Labels: fixing

#774 Added notebook to demonstrate sparse inference acceleration on 4th Gen Xeon
  README.md
  README_cn.md
  notebooks/116-sparsity-optimization/116-sparsity-optimization.ipynb
  notebooks/116-sparsity-optimization/README.md
  notebooks/README.md
Labels: new notebook

#778 resolve documentation build issues
  .ci/convert_notebooks.sh
  .github/workflows/convert_notebooks.yml
  notebooks/107-speech-recognition-quantization/107-speech-recognition-quantization.ipynb
  notebooks/110-ct-segmentation-quantize/pytorch-monai-training.ipynb
  notebooks/113-image-classification-quantization/113-image-classification-quantization.ipynb
  notebooks/114-quantization-simplified-mode/114-quantization-simplified-mode.ipynb
  notebooks/226-yolov7-optimization/226-yolov7-optimization.ipynb
  notebooks/227-whisper-subtitles-generation/227-whisper-subtitles-generation.ipynb
  requirements.txt
Labels: fixing

#751 Add 407-person-tracking-webcam
  README.md
  notebooks/407-person-tracking-webcam/407-person-tracking.ipynb
  notebooks/407-person-tracking-webcam/README.md
  notebooks/407-person-tracking-webcam/deepsort_utils/detection.py
  notebooks/407-person-tracking-webcam/deepsort_utils/iou_matching.py
  notebooks/407-person-tracking-webcam/deepsort_utils/kalman_filter.py
  notebooks/407-person-tracking-webcam/deepsort_utils/linear_assignment.py
  notebooks/407-person-tracking-webcam/deepsort_utils/nn_matching.py
  notebooks/407-person-tracking-webcam/deepsort_utils/track.py
  notebooks/407-person-tracking-webcam/deepsort_utils/tracker.py
  notebooks/README.md
  notebooks/data/image/person_1_1.png
  notebooks/data/image/person_1_2.png
  notebooks/data/image/person_2_1.png
  notebooks/data/video/people.mp4
Labels: new notebook

#796 add instruct pix2pix notebook
  .github/workflows/nbval_precommit.yml
  README.md
  notebooks/231-instruct-pix2pix-image-editing/231-instruct-pix2pix-image-editing.ipynb
  notebooks/231-instruct-pix2pix-image-editing/README.md
  notebooks/README.md
Labels: new notebook

#785 107: add data2vec support
  README.md
  notebooks/107-speech-recognition-quantization/107-speech-recognition-quantization-data2vec.ipynb
  notebooks/107-speech-recognition-quantization/107-speech-recognition-quantization-wav2vec2.ipynb
  notebooks/107-speech-recognition-quantization/README.md
  notebooks/116-sparsity-optimization/116-sparsity-optimization.ipynb
  notebooks/README.md
Labels: new notebook
