Repository openvinotoolkit/openvino_notebooks, pull requests merged in 2023-03, with the labels that each got.

#866 BLIP: visual language processing notebook
  README.md
  notebooks/233-blip-visual-language-processing/233-blip-visual-language-processing.ipynb
  notebooks/233-blip-visual-language-processing/README.md
  notebooks/README.md
Labels: new notebook

#864 Encodec notebook
  README.md
  notebooks/234-encodec-audio-compression/234-encodec-audio-compression.ipynb
  notebooks/234-encodec-audio-compression/README.md
  notebooks/234-encodec-audio-compression/requirements.txt
  notebooks/README.md
Labels: new notebook

#891 Merging 210 to 110 family
  .github/workflows/convert_notebooks.yml
  .github/workflows/nbval.yml
  .github/workflows/nbval_precommit.yml
  README.md
  README_cn.md
  notebooks/110-ct-segmentation-quantize/110-ct-scan-live-inference.ipynb
  notebooks/110-ct-segmentation-quantize/110-ct-segmentation-quantize-nncf.ipynb
  notebooks/110-ct-segmentation-quantize/110-ct-segmentation-quantize.ipynb
  notebooks/110-ct-segmentation-quantize/README.md
  notebooks/110-ct-segmentation-quantize/async_pipeline.py
  notebooks/110-ct-segmentation-quantize/custom_segmentation.py
  notebooks/110-ct-segmentation-quantize/data-preparation-ct-scan.ipynb
  notebooks/110-ct-segmentation-quantize/pretrained_model/quantized_unet_kits19.bin
  notebooks/110-ct-segmentation-quantize/pretrained_model/quantized_unet_kits19.xml
  notebooks/110-ct-segmentation-quantize/pretrained_model/unet_kits19.bin
  notebooks/110-ct-segmentation-quantize/pretrained_model/unet_kits19.xml
  notebooks/110-ct-segmentation-quantize/pytorch-monai-training.ipynb
  notebooks/210-ct-scan-live-inference/README.md
  notebooks/210-ct-scan-live-inference/requirements.txt
  notebooks/README.md
  notebooks/utils/models/__init__.py
  notebooks/utils/models/model.py
  notebooks/utils/notebook_utils.ipynb
  notebooks/utils/notebook_utils.py
Labels: enhancement

#895 Clear explanation about applying a token
  notebooks/225-stable-diffusion-text-to-image/225-stable-diffusion-text-to-image.ipynb
Labels: documentation

#896 Fix for docs
  notebooks/117-model-server/117-model-server.ipynb
Labels: fixing

#898 Fix for documentation generation once again
  notebooks/234-encodec-audio-compression/234-encodec-audio-compression.ipynb
Labels: fixing

#893 Move 110-ct-scan-live-inference on AsyncInferQueue
  notebooks/110-ct-segmentation-quantize/110-ct-scan-live-inference.ipynb
Labels: enhancement

#910 fix issues running on docker ci
  notebooks/211-speech-to-text/211-speech-to-text.ipynb
  notebooks/215-image-inpainting/215-image-inpainting.ipynb
Labels: fixing

#920 Remove all non-printable characters
  .ci/convert_notebooks.py
Labels: documentation, fixing

#927 Fix 116 multiline bash command
  notebooks/116-sparsity-optimization/116-sparsity-optimization.ipynb
Labels: documentation, fixing

#942 Removing yaspin from dependencies
  .docker/Pipfile
  .docker/Pipfile.lock
  notebooks/110-ct-segmentation-quantize/110-ct-segmentation-quantize.ipynb
  notebooks/111-detection-quantization/111-detection-quantization.ipynb
  notebooks/208-optical-character-recognition/208-optical-character-recognition.ipynb
  requirements.txt
Labels: dependencies

#944 [README] Remove hidden content and file duplicate
  README.md
  README_cn.md
  notebooks/110-ct-segmentation-quantize/README.md
  notebooks/202-vision-superresolution/README.md
  notebooks/224-3D-segmentation-point-clouds/README.md
  notebooks/225-stable-diffusion-text-to-image/README.md
  notebooks/230-yolov8-optimization/README.md
  notebooks/231-instruct-pix2pix-image-editing/README.md
  notebooks/232-clip-language-saliency-map/README.md
  notebooks/233-blip-visual-language-processing/README.md
  notebooks/401-object-detection-webcam/README.md
  notebooks/402-pose-estimation-webcam/README.md
  notebooks/405-paddle-ocr-webcam/README.md
  notebooks/407-person-tracking-webcam/README.md
  notebooks/README.md
Labels: documentation

#946 Update README_cn.md
  README.md
  README_cn.md
Labels: documentation
